<tr>
	<th style="width:300px;"><label for="cdn_rscf_user">Username:</label></th>
	<td>
		<input id="cdn_rscf_user" type="text" name="cdn.rscf.user" value="<?php echo htmlspecialchars($this->_config->get_string('cdn.rscf.user')); ?>" size="30" />
	</td>
</tr>
<tr>
	<th><label for="cdn_rscf_key"><acronym title="Application Programming Interface">API</acronym> key:</label></th>
	<td>
		<input id="cdn_rscf_key" type="password" name="cdn.rscf.key" value="<?php echo htmlspecialchars($this->_config->get_string('cdn.rscf.key')); ?>" size="60" />
	</td>
</tr>
<tr>
	<th><label for="cdn_rscf_container">Container:</label></th>
	<td>
		<input id="cdn_rscf_container" type="text" name="cdn.rscf.container" value="<?php echo htmlspecialchars($this->_config->get_string('cdn.rscf.container')); ?>" size="30" />
		<input id="cdn_create_container" class="button cdn_rscf" type="button" value="Create container" />
		<span id="cdn_create_container_status" class="w3tc-status w3tc-process"></span>
	</td>
</tr>
<tr>
    <th><label for="cdn_rscf_id">Replace site's hostname with:</label></th>
    <td>
		<input id="cdn_rscf_id" type="text" name="cdn.rscf.id" value="<?php echo htmlspecialchars($this->_config->get_string('cdn.rscf.id')); ?>" size="18" style="text-align:right;" />.cloudfiles.rackspacecloud.com or CNAME:
		<?php $cnames = $this->_config->get_array('cdn.rscf.cname'); include W3TC_DIR . '/inc/options/cdn/common/cnames.phtml'; ?>
    </td>
</tr>
<tr>
	<th colspan="2">
        <input id="cdn_test" class="button cdn_rscf" type="button" value="Test Cloud Files upload" /> <span id="cdn_test_status" class="w3tc-status w3tc-process"></span>
    </th>
</tr>
